package:
  name: baker-rust
  version: 0.1.0
  epoch: 0
  description: "Rust implementation of BakerCM"
  copyright:
    - license: BSD-3-Clause
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - git
      - pkgconf
      - rust

pipeline:
  - runs: |
      cargo build --release
  - runs: |
      BIN="$(find target -type f -path '*/release/baker-rust' | head -n1)"
      if [ -z "$BIN" ]; then
        echo "baker-rust binary not found under target/*/release" >&2
        exit 1
      fi
      install -Dm755 "$BIN" "${{targets.destdir}}/usr/bin/baker-rust"
      install -Dm644 README.md "${{targets.destdir}}/usr/share/doc/baker-rust/README.md"
      install -Dm644 LICENSE "${{targets.destdir}}/usr/share/licenses/baker-rust/LICENSE"
  - uses: strip
